# Generated by Django 5.1.2 on 2024-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgResponseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
