# Generated by Django 5.1.3 on 2024-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_devopsmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsmetrics',
            name='metric_value',
            field=models.TextField(default='0'),
        ),
    ]
