# Generated by Django 5.1.3 on 2024-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_devopsmetrics_metric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsmetrics',
            name='metric_value',
            field=models.FloatField(default=0.0),
        ),
    ]
