# Generated by Django 5.1.3 on 2024-12-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_devopsmetrics_metric_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvgChatLength',
        ),
        migrations.DeleteModel(
            name='AvgResponseTime',
        ),
        migrations.DeleteModel(
            name='Counters',
        ),
    ]
